sudo: required

services:
  - docker

before_install:
  - docker build -t celoka/fibonnaci-app-test -f ./client/Dockerfile.dev ./client

script:
  - docker run celoka/fibonnaci-app-test npm test -- --coverage

after_success:
  - docker build -t celoka/fibonnaci-app-client ./client
  - docker build -t celoka/fibonnaci-app-nginx ./nginx
  - docker build -t celoka/fibonnaci-app-server ./server
  - docker build -t celoka/fibonnaci-app-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push all built images to docker hub
  - docker push celoka/fibonnaci-app-client
  - docker push celoka/fibonnaci-app-nginx
  - docker push celoka/fibonnaci-app-server
  - docker push celoka/fibonnaci-app-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: fibonnaci-app
  env: FibonnaciApp-env
  bucket_name: elasticbeanstalk-us-east-2-758010155601
  bucket_path: fibonnaci-app
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure:  "$AWS_SECRET_KEY"
